FROM landoop/fast-data-dev:latest

COPY gcs.json /opt/gcs.json
COPY confluentinc-kafka-connect-gcs-5.0.1/lib/ /opt/landoop/connectors/third-party/kafka-connect-gcs/
COPY confluentinc-kafka-connect-kinesis-1.1.1-preview/lib/ /opt/landoop/connectors/third-party/kafka-connect-kinesis/
